services:
  - type: web
    name: kazinvest
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production